name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: List all shell scripts found
      run: find . -type f -name '*.sh'

    - name: Run ShellCheck on all shell scripts
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        shellcheck_args: "--enable=all"
